Repository livecode/livecode-ide, pull requests merged in 2018-05, with the labels that each got.

#1973 [Bug 18585] Ensure Dictionary traps cmd+A
  Toolset/palettes/dictionary/behaviors/revdictionarybehavior.livecodescript
  notes/bugfix-18585.md
Labels: bug, vulcan/reviewed

#1972 [Bug 21222] Ensure File->Close is disabled when topstack=revMenubar
  Toolset/palettes/menubar/revmenubar.livecodescript
  notes/bugfix-21222.md
Labels: bug, vulcan/reviewed

#1969 [[ Dictionary ]] Turn off search field spell check
  Documentation/html_viewer/api.html.template
Labels: enhancement, vulcan/reviewed

#1977 Merge develop 9.0 22.05.2018
  Documentation/guides/LiveCode Data Grid.md
  Toolset/libraries/revcommonlibrary.livecodescript
  Toolset/libraries/revidelibrary.8.livecodescript
  Toolset/palettes/dictionary/behaviors/revdictionarybehavior.livecodescript
  Toolset/palettes/extension manager/revideextensionmanagerrowbehavior.livecodescript
  Toolset/palettes/menubar/revmenubar.livecodescript
  Toolset/palettes/revfileassociations.livecode
  Toolset/palettes/script editor/behaviors/revsecommoneditorbehavior.livecodescript
  Toolset/palettes/script editor/behaviors/revseeditorbehavior.livecodescript
  Toolset/palettes/script editor/behaviors/revsefindmaincardbehavior.livecodescript
  Toolset/palettes/script editor/behaviors/revsestackbehavior.livecodescript
  notes/bugfix-18585.md
  notes/bugfix-20094.md
  notes/bugfix-21167.md
  notes/bugfix-21169.md
  notes/bugfix-21172.md
  notes/bugfix-21174.md
  notes/bugfix-21176.md
  notes/bugfix-21179.md
  notes/bugfix-21202.md
  notes/bugfix-21206.md
  notes/bugfix-21222.md
  tests/messagebox/execution.livecodescript
Labels: pr/clean-merge, vulcan/reviewed

#1974 [[ PERF ]] Ide performance issues
  Toolset/palettes/message box/behaviors/revmessageboxbehavior.livecodescript
  Toolset/palettes/message box/behaviors/revmessageboxsinglelinecardbehavior.livecodescript
  Toolset/palettes/message box/behaviors/revmessageboxsinglelinemessagebehavior.livecodescript
  Toolset/palettes/script editor/behaviors/revsecommoneditorbehavior.livecodescript
Labels: bug, enhancement, vulcan/reviewed

#1978 [[ Bug 20672 ]] Update property inspector once for multiple objects
  Toolset/palettes/inspector/revinspectortemplate.livecodescript
  notes/bugfix-20672.md
Labels: bug, vulcan/reviewed

#1979 [[Bug 21323]] syntax for DG2 new props incorrect
  Documentation/dictionary/datagrid.lcdoc
  notes/bugfix-21323.md
Labels: bug, vulcan/reviewed
