Repository livecode/livecode-ide, pull requests merged in 2018-03, with the labels that each got.

#1921 [Bug 21022] Ensure nested groups' scripts can be searched
  Toolset/palettes/script editor/behaviors/revseeditorbehavior.livecodescript
  notes/bugfix-21022.md
Labels: bug, vulcan/reviewed

#1917 [[ Bug 20928 ]] MultipleHilites is MultipleLines where it should not
  Toolset/resources/supporting_files/property_definitions/propertyInfo.tsv
Labels: bug, vulcan/reviewed

#1918 [[ Bug 20888]] Tree view doesn't allow comma in keys
  Toolset/palettes/inspector/editors/com.livecode.pi.array.behavior.livecodescript
Labels: bug, vulcan/reviewed

#1916 [Bug 20647] Ensure Dictionary traps cmd+W
  Toolset/palettes/dictionary/behaviors/revdictionarybehavior.livecodescript
  notes/bugfix-20647.md
Labels: bug, vulcan/reviewed

#1905 [[ Bug 20857 ]] Fix widget property ordering in inspector
  Toolset/libraries/revideextensionlibrary.livecodescript
  notes/bugfix-20857.md
Labels: bug, vulcan/reviewed

#1920 Bugfix extension package utils
  Toolset/home.livecodescript
  Toolset/libraries/revidedeveloperextensionlibrary.livecodescript
  Toolset/libraries/revideextensionlibrary.livecodescript
  Toolset/libraries/revidelibrary.8.livecodescript
  Toolset/libraries/revinitialisationlibrary.livecodescript
  Toolset/palettes/extension builder/revextensionbuilderbehavior.livecodescript
Labels: vulcan/reviewed

#1923 [[ Bug ]] Ensure ide extension lib can find extension-utils
  Toolset/libraries/revideextensionlibrary.livecodescript
Labels: bug, vulcan/reviewed

#1924 [[ Bug 19013 ]] Default PI color picker to RGB
  Toolset/palettes/inspector/editors/com.livecode.pi.color.behavior.livecodescript
  notes/bugfix-19013.md
Labels: P-property-inspector, bug, vulcan/reviewed

#1925 [[ Bug ]] Ensure support files are full paths when compiling
  Toolset/libraries/revidedeveloperextensionlibrary.livecodescript
  Toolset/libraries/revideextensionlibrary.livecodescript
Labels: bug, vulcan/reviewed

#1932 [[ Bug 19741 ]] Remove legacy inks from PI
  Toolset/resources/supporting_files/property_definitions/propertyInfo.tsv
  notes/bugfix-19741.md
Labels: cleanup, vulcan/reviewed

#1930 [[ ExtensionBuilder ]] Ensure rect preservation still works
  Toolset/libraries/revidedeveloperextensionlibrary.livecodescript
Labels: bug, vulcan/reviewed

#1929 [[ DataGrid2 ]] Allow swipe and hold
  Toolset/palettes/revdatagridlibrary/behaviorsrowchainedbehavior.livecodescript
Labels: vulcan/reviewed

#1931 Amend .gitignore to exclude dictionary data
  .gitignore
Labels: vulcan/reviewed

#1926 [Bug 21044] Prevent loss of trailing empty lines by formatting script
  Toolset/palettes/script editor/behaviors/revsecommoneditorbehavior.livecodescript
  notes/bugfix-21044.md
Labels: vulcan/reviewed

#1933 [Bug 8704] Search in the correct location for the autoupdater on Linux
  Toolset/libraries/revidelibrary.8.livecodescript
  notes/bugfix-8704.md
Labels: bug, vulcan/reviewed

#1927 [Bug 20621] Refine indentation for some if variants
  Toolset/palettes/script editor/behaviors/revsecommoneditorbehavior.livecodescript
Labels: vulcan/reviewed

#1928 additional if variant
  tests/scripteditor/_indentation_tests/if.livecodescript
Labels: vulcan/reviewed

#1936 [[ Bug 20979 ]] Escape & in recent and window lists
  Toolset/palettes/menubar/revmenubar.livecodescript
  notes/bugfix-20979.md
Labels: bug, vulcan/reviewed

#1922 [[ Docs ]] Update Extending LiveCode guide
  Documentation/guides/Extending LiveCode.md
  Documentation/guides/images/extensions_canvas_elliptic_arc.png
  Documentation/guides/images/extensions_canvas_parallel_lines.png
  Documentation/guides/images/extensions_canvas_svgpath.png
Labels: documentation, vulcan/reviewed

#1938 [[ Bug 21082 ]] Ensure errors are thrown when failing to validate ext package
  Toolset/libraries/revideextensionlibrary.livecodescript
  notes/bugfix-21082.md
Labels: bug, vulcan/reviewed

#1942 [[ Bug 21090 ]] Create DG2 template controls with msgs unlocked
  Toolset/palettes/revdatagridlibrary/behaviorsdatagridbuttonbehavior.livecodescript
  notes/bugfix-21090.md
Labels: bug, vulcan/reviewed

#1934 [[ Bug 21032 ]] Relayer iOS settings tab button below controls
  Toolset/palettes/standalone settings/revstandalonesettingsiosbehavior.livecodescript
  notes/bugfix-21032.md
Labels: bug, vulcan/reviewed

#1944 [Bug 21100] Ensure we restore the defaultstack when opening stack revVariableVisualizer
  Toolset/palettes/script editor/behaviors/revsevariablespanebehavior.livecodescript
  notes/bugfix-21100.md
Labels: bug, vulcan/reviewed

#1937 [[ Bug 21065 ]] Don't try to set loc of stack to empty
  Toolset/libraries/revidedeveloperextensionlibrary.livecodescript
  notes/bugfix-21065.md
Labels: vulcan/reviewed

#1939 [[ Bug 21093 ]] Handle thrown errors
  Toolset/libraries/revdebuggerlibrary.livecodescript
  Toolset/libraries/revidelibrary.8.livecodescript
  notes/bugfix-21093.md
Labels: bug, vulcan/reviewed

#1940 [Bug 21086] Keep correct selection when formatting script
  Toolset/palettes/script editor/behaviors/revsecommoneditorbehavior.livecodescript
  notes/bugfix-21086.md
Labels: bug, vulcan/reviewed

#1941 [[ Bug 21095 ]] Load required extensions on startup
  Toolset/libraries/revideextensionlibrary.livecodescript
  Toolset/palettes/extension manager/revideextensionmanagerrowbehavior.livecodescript
  notes/bugfix-21095.md
Labels: bug, vulcan/reviewed

#1949 [[ Bug 21116 ]] Ensure table style DG has mobile scrollers
  Toolset/palettes/revdatagridlibrary/behaviorsdatagridbuttonbehavior.livecodescript
  notes/bugfix-21116.md
Labels: bug, vulcan/reviewed

#1946 Merge release-9.0.0 22.03.2018
  Toolset/libraries/revidedeveloperextensionlibrary.livecodescript
  Toolset/libraries/revideextensionlibrary.livecodescript
  Toolset/palettes/revdatagridlibrary/behaviorsdatagridbuttonbehavior.livecodescript
  Toolset/palettes/script editor/behaviors/revsevariablespanebehavior.livecodescript
  Toolset/palettes/standalone settings/revstandalonesettingsiosbehavior.livecodescript
  notes/bugfix-21032.md
  notes/bugfix-21065.md
  notes/bugfix-21082.md
  notes/bugfix-21090.md
  notes/bugfix-21100.md
Labels: pr/clean-merge

#1950 Merge develop 8.1 28.03.2018
  Toolset/palettes/dictionary/behaviors/revdictionarybehavior.livecodescript
  notes/bugfix-20647.md
Labels: pr/clean-merge, vulcan/reviewed

#1951 [[ StandaloneSettings ]] Remove experimental warning from html5 build pane
  Toolset/palettes/standalone settings/revstandalonesettings.8.rev
Labels: vulcan/reviewed

#1953 Merge develop 9.0 28.03.2018
  Toolset/libraries/revdebuggerlibrary.livecodescript
  Toolset/libraries/revidedeveloperextensionlibrary.livecodescript
  Toolset/libraries/revideextensionlibrary.livecodescript
  Toolset/libraries/revidelibrary.8.livecodescript
  Toolset/palettes/dictionary/behaviors/revdictionarybehavior.livecodescript
  Toolset/palettes/extension manager/revideextensionmanagerrowbehavior.livecodescript
  Toolset/palettes/revdatagridlibrary/behaviorsdatagridbuttonbehavior.livecodescript
  Toolset/palettes/script editor/behaviors/revsecommoneditorbehavior.livecodescript
  Toolset/palettes/script editor/behaviors/revsevariablespanebehavior.livecodescript
  Toolset/palettes/standalone settings/revstandalonesettings.8.rev
  Toolset/palettes/standalone settings/revstandalonesettingsiosbehavior.livecodescript
  notes/bugfix-20647.md
  notes/bugfix-21032.md
  notes/bugfix-21065.md
  notes/bugfix-21082.md
  notes/bugfix-21086.md
  notes/bugfix-21090.md
  notes/bugfix-21093.md
  notes/bugfix-21095.md
  notes/bugfix-21100.md
  notes/bugfix-21116.md
Labels: pr/clean-merge, vulcan/reviewed
