Repository livecode/livecode-ide, pull requests merged in 2018-02, with the labels that each got.

#1909 [[ Bug ]] Add player mirrored property to PI
  Toolset/resources/supporting_files/property_definitions/com.livecode.interface.classic.Player.tsv
  Toolset/resources/supporting_files/property_definitions/propertyInfo.tsv
Labels: bug, vulcan/reviewed

#1911 [Bug 20806] PI scroller should not intercept Home/End keys if the target is a PI field
  Toolset/palettes/inspector/revinspectortemplate.livecodescript
  notes/bugfix-20806.md
Labels: bug, vulcan/reviewed

#1910 [[ Bug 20951 ]] Fix IDE files
  Toolset/home.livecodescript
Labels: vulcan/reviewed

#1908 [Bug 20794] Show warning when using map widget on OSX 10.9 and 10.10
  Toolset/libraries/revidelibrary.8.livecodescript
  notes/bugfix-20794.md
Labels: bug, vulcan/reviewed

#1891 [[ Bug 20901 ]] Fix issues with users' extension guides
  Documentation/html_viewer/js/guide_functions.js
  Toolset/libraries/revidelibrary.8.livecodescript
  notes/bugfix-20901.md
Labels: bug, vulcan/reviewed

#1887 [[ Store ]] Output manifest.xml when packaging LCS extensions
  Toolset/libraries/revidedeveloperextensionlibrary.livecodescript
  Toolset/libraries/revideextensionlibrary.livecodescript
Labels: WIP

#1894 [[ Bug 20909 ]] Use autoformat preference for indent
  Toolset/palettes/script editor/behaviors/revsecommoneditorbehavior.livecodescript
  Toolset/palettes/script editor/behaviors/revsemenubarbehavior.livecodescript
  notes/bugfix-20909.md
Labels: bug, vulcan/reviewed

#1912 [[ Bug ]] Fix extension 'file' property
  Toolset/libraries/revideextensionlibrary.livecodescript
Labels: bug, vulcan/reviewed

#1897 [bug 17819] enable cmd+c in dictionary enhanced
  Toolset/palettes/dictionary/behaviors/revdictionarybehavior.livecodescript
Labels: vulcan/reviewed

#1864 [[ Bug ]] Ensure dictionary gen ignores protected stacks
  Toolset/libraries/revidelibrary.8.livecodescript
Labels: bug, vulcan/reviewed

#1913 [[ Bug 20991 ]] Use win32 for code library path
  Toolset/libraries/revideextensionlibrary.livecodescript
Labels: bug, vulcan/reviewed

#1914 Merge develop 8.1 20.02.18
  Toolset/palettes/dictionary/behaviors/revdictionarybehavior.livecodescript
Labels: pr/clean-merge, vulcan/reviewed

#1902 [[ Emscripten ]] Add com.livecode.emscripten to list of builtin extensions
  Toolset/libraries/revideextensionlibrary.livecodescript
Labels: bug, enhancement, vulcan/reviewed

#1919 [Bug 21014] Fix installing extensions from local .lce files
  Toolset/libraries/revideextensionlibrary.livecodescript
  Toolset/palettes/extension manager/revideextensionmanagerbehavior.livecodescript
  notes/bugfix-21014.md
Labels: blocker, bug, vulcan/reviewed

#1915 [[ CodeLibrary ]] Fix library mapping for installed extensions
  Toolset/libraries/revideextensionlibrary.livecodescript
Labels: bug, vulcan/reviewed
