Repository livecode/livecode-ide, pull requests merged in 2018-08, with the labels that each got.

#1988 [[Feature]] Add OS and Platforms to LCB Metadata
  Documentation/guides/Extending LiveCode.md
  Toolset/libraries/revidedeveloperextensionlibrary.livecodescript
Labels: vulcan/reviewed

#1990 [[ Android Archs ]] Add multiple android archs to IDE
  Toolset/palettes/standalone settings/revstandalonesettings.8.rev
  Toolset/palettes/standalone settings/revstandalonesettingsandroidbehavior.livecodescript
Labels: enhancement

#1975 [[ bugfix-20121 ]] Icon Picker: Use a popup stack for icon property
  Toolset/palettes/inspector/editors/com.livecode.pi.svgicon.behavior.livecodescript
  Toolset/palettes/inspector/editors/com.livecode.pi.svgiconfilter.behavior.livecodescript
  Toolset/palettes/inspector/editors/com.livecode.pi.svgiconfilter.livecode
  notes/bugfix-20121.md
Labels: pr/binary, vulcan/reviewed

#1971 [[ Bug 21245 ]] SE indent errors with inline block comments
  Toolset/palettes/script editor/behaviors/revsecommoneditorbehavior.livecodescript
  notes/bugfix-21245.md
  tests/scripteditor/_indentation_tests/bug-21245.livecodescript
Labels: vulcan/reviewed

#1992 Ensure arrowKeys work correctly when editing names in PB
  Toolset/palettes/project browser/revprojectbrowserbehavior.livecodescript
  notes/bugfix-21430.md
Labels: bug, vulcan/reviewed

#1989 [[ Bug 21484 ]] Allow scroll wheel to work in PI text fields
  Toolset/palettes/inspector/behaviors/revinspectoreditorbehavior.livecodescript
  notes/bugfix-21484.md
Labels: vulcan/reviewed

#1985 [[ Extensions ]] Add support for snippets and sample stacks
  Toolset/libraries/revideextensionlibrary.livecodescript
  Toolset/libraries/revidelibrary.8.livecodescript
  Toolset/palettes/extension manager/revideextensionmanagerbehavior.livecodescript
  Toolset/palettes/extension manager/revideextensionmanagerlistbehavior.livecodescript
  Toolset/palettes/extension manager/revideextensionmanagerrowbehavior.livecodescript
  Toolset/palettes/script editor/behaviors/revseutilities.livecodescript
  Toolset/palettes/snippet viewer/behaviors/revidesnippetviewerbehavior.livecodescript
  Toolset/palettes/snippet viewer/revidesnippetviewer.livecode
Labels: vulcan/reviewed
