Repository livecode/livecode-ide, pull requests merged in 2018-12, with the labels that each got.

#2014 [21247] Fix setting PB Prefs from LC Preferences pane
  Toolset/palettes/revpreferencesgui.rev
  notes/bugfix-21247.md
Labels: bug, pr/binary, vulcan/reviewed

#2016 [Bug 21721] Keep Selection when formatting handler
  Toolset/palettes/script editor/behaviors/revsecommoneditorbehavior.livecodescript
  notes/bugfix-21721.md
Labels: vulcan/reviewed

#2019 [Bug 21379] [NavBar PI] Fix setting an itemName when more than 9 items
  Toolset/palettes/inspector/editors/com.livecode.pi.editorlist.behavior.livecodescript
  notes/bugfix-21379.md
Labels: bug, vulcan/reviewed
