Repository livecode/livecode-ide, pull requests merged in 2018-06, with the labels that each got.

#1980 Removed text that shouldn't be seen in syntaxes
  Documentation/dictionary/datagrid.lcdoc
Labels: vulcan/reviewed

#1982 [[ Bug ]] Fix colorization of msg box autocomplete
  Toolset/palettes/message box/behaviors/revmessageboxsinglelinemessagebehavior.livecodescript
Labels: bug, vulcan/reviewed

#1983 Merge develop 9.0 05.06.18
  Documentation/dictionary/datagrid.lcdoc
  Toolset/palettes/inspector/revinspectortemplate.livecodescript
  Toolset/palettes/message box/behaviors/revmessageboxbehavior.livecodescript
  Toolset/palettes/message box/behaviors/revmessageboxsinglelinecardbehavior.livecodescript
  Toolset/palettes/message box/behaviors/revmessageboxsinglelinemessagebehavior.livecodescript
  Toolset/palettes/script editor/behaviors/revsecommoneditorbehavior.livecodescript
  notes/bugfix-20672.md
  notes/bugfix-21323.md
Labels: pr/clean-merge, vulcan/reviewed

#1981 [[ Bug 21232 ]] Fix wandering breakpoints
  Toolset/palettes/script editor/behaviors/revsecommoneditorbehavior.livecodescript
  Toolset/palettes/script editor/behaviors/revsegutterbehavior.livecodescript
  notes/bugfix-21232.md
Labels: bug, vulcan/reviewed

#1984 [[ Bug 4382 ]] Add `Clear Recent Files` option to Open Recent File menu
  Toolset/palettes/menubar/revmenubar.livecodescript
  notes/bugfix-4382.md
Labels: enhancement, vulcan/reviewed

#1976 [Bug 21171] Ensure unicode characters in app label are shown correctly
  Toolset/palettes/standalone settings/revstandalonesettings.8.rev
  Toolset/palettes/standalone settings/revstandalonesettingsandroidbehavior.livecodescript
Labels: bug, pr/binary, vulcan/reviewed
