Repository livecode/livecode-ide, pull requests merged in 2018-04, with the labels that each got.

#1954 [[ Bug 21122 ]] Update windowBoundingRect
  Toolset/libraries/revidelibrary.8.livecodescript
  Toolset/palettes/menubar/revmenubar.livecodescript
  Toolset/palettes/tools/revtools.livecodescript
  notes/bugfix-21122.md
Labels: bug, vulcan/reviewed

#1947 [[ Bug 19998 ]] Add default points for polygon graphic
  Toolset/resources/supporting_files/property_definitions/com.livecode.interface.classic.PolygonGraphic.tsv
  notes/bugfix-19998.md
Labels: bug, vulcan/reviewed

#1945 [[ Extensions ]] Detect missing dependencies when installing package
  Toolset/libraries/revideextensionlibrary.livecodescript
Labels: vulcan/reviewed

#1943 [[ Bug 19504 ]] Allow tab in text property of PI
  Toolset/palettes/inspector/editors/com.livecode.pi.text.behavior.livecodescript
  Toolset/resources/supporting_files/property_definitions/propertyInfo.tsv
  notes/bugfix-19504.md
Labels: bug, vulcan/reviewed

#1935 [[ Bug 21017 ]] Skip tracing resizeControl
  Toolset/libraries/revdebuggerlibrary.livecodescript
  notes/bugfix-21017.md
Labels: bug, vulcan/reviewed

#1955 Merge develop 9.0 09.04.18
  Toolset/libraries/revdebuggerlibrary.livecodescript
  Toolset/libraries/revideextensionlibrary.livecodescript
  Toolset/libraries/revidelibrary.8.livecodescript
  Toolset/palettes/inspector/editors/com.livecode.pi.text.behavior.livecodescript
  Toolset/palettes/menubar/revmenubar.livecodescript
  Toolset/palettes/tools/revtools.livecodescript
  Toolset/resources/supporting_files/property_definitions/com.livecode.interface.classic.PolygonGraphic.tsv
  Toolset/resources/supporting_files/property_definitions/propertyInfo.tsv
  notes/bugfix-19504.md
  notes/bugfix-19998.md
  notes/bugfix-21017.md
  notes/bugfix-21122.md
Labels: pr/clean-merge, vulcan/reviewed

#1961 [Bug 21176] Make sure Upgrade Options can always be shown
  Toolset/palettes/menubar/revmenubar.livecodescript
  notes/bugfix-21176.md
Labels: bug, vulcan/reviewed

#1960 [[ Bug 21172 ]] Fix revMail on mobile
  Toolset/libraries/revcommonlibrary.livecodescript
  notes/bugfix-21172.md
Labels: bug, vulcan/reviewed

#1959 [21169] Ensure splash screen always hides on Windows
  Toolset/palettes/revfileassociations.livecode
  notes/bugfix-21169.md
Labels: bug, pr/binary, vulcan/reviewed

#1957 [Bug 21167] Ensure Replace history is remembered
  Toolset/palettes/script editor/behaviors/revsefindmaincardbehavior.livecodescript
  notes/bugfix-21167.md
Labels: bug, vulcan/reviewed

#1948 [[ Bug 20094 ]] Execute msg box if it compiles
  Toolset/libraries/revidelibrary.8.livecodescript
  notes/bugfix-20094.md
  tests/messagebox/execution.livecodescript
Labels: bug, vulcan/reviewed

#1964 Fix runtime error preventing splash screen from hiding
  Toolset/palettes/revfileassociations.livecode
Labels: bug, pr/binary, vulcan/reviewed

#1956 [Bug 21174] Ensure "Sample Stacks" stack does show up in menu "Windows"
  Toolset/libraries/revidelibrary.8.livecodescript
  Toolset/palettes/menubar/revmenubar.livecodescript
  notes/bugfix-21174.md
Labels: bug, vulcan/reviewed

#1963 Fixed typo causing runtime error
  Toolset/palettes/menubar/revmenubar.livecodescript
Labels: bug, vulcan/reviewed

#1966 [[ Bug 21202 ]] Fix deselection of next find after replace
  Toolset/palettes/script editor/behaviors/revsecommoneditorbehavior.livecodescript
  Toolset/palettes/script editor/behaviors/revseeditorbehavior.livecodescript
  notes/bugfix-21202.md
Labels: bug, vulcan/reviewed

#1967 [[ Bug 21179 ]] Add show documentation to extension context menu
  Toolset/libraries/revidelibrary.8.livecodescript
  Toolset/palettes/extension manager/revideextensionmanagerrowbehavior.livecodescript
  notes/bugfix-21179.md
Labels: bug, vulcan/reviewed

#1958 [[ DataGridGuide ]] Remove trailing header #s
  Documentation/guides/LiveCode Data Grid.md
Labels: documentation, vulcan/reviewed
