Repository livecode/livecode-ide, pull requests merged in 2019-04, with the labels that each got.

#2049 Merge develop 9.0 28.03.2019
  Toolset/home.livecodescript
  Toolset/libraries/revidelibrary.8.livecodescript
  Toolset/palettes/extension manager/revideextensionmanager.livecode
  Toolset/palettes/inspector/editors/com.livecode.pi.dimension.livecode
  Toolset/palettes/inspector/editors/com.livecode.pi.graphiceffect.livecode
  Toolset/palettes/inspector/editors/com.livecode.pi.number.livecode
  Toolset/palettes/inspector/editors/com.livecode.pi.pattern.livecode
  Toolset/palettes/inspector/editors/com.livecode.pi.point.livecode
  Toolset/palettes/inspector/editors/com.livecode.pi.script.livecode
  Toolset/palettes/inspector/editors/com.livecode.pi.string.livecode
  Toolset/palettes/message box/revmessagebox.8.rev
  Toolset/palettes/project browser/behaviors/revideprojectbrowsercontainerrowbehavior.livecodescript
  Toolset/palettes/revCore.8.livecode
  Toolset/palettes/standalone settings/revstandalonesettings.8.rev
  Toolset/palettes/standalone settings/revstandalonesettingsbehavior.livecodescript
  Toolset/palettes/standalone settings/revstandalonesettingsiosbehavior.livecodescript
  notes/bugfix-15157.md
  notes/bugfix-17152.md
  notes/bugfix-21809.md
  notes/bugfix-21841.md
  notes/bugfix-21885.md
Labels: pr/binary, vulcan/reviewed

#2046 [Bug 21896] Fix Autocomplete IF-structs
  Toolset/palettes/script editor/behaviors/revsecommoneditorbehavior.livecodescript
  notes/bugfix-21896.md
Labels: vulcan/reviewed

#2048 [[ Bug ]] Fix android binaries when BFS
  Toolset/home.livecodescript
Labels: bug, vulcan/reviewed

#2035 [21834] - Project browser fix display errors for missing behaviors, add alert
  Toolset/palettes/project browser/behaviors/revideprojectbrowsercontainerrowbehavior.livecodescript
  Toolset/palettes/project browser/behaviors/revideprojectbrowsercontrolrowbehavior.livecodescript
  Toolset/palettes/project browser/behaviors/revideprojectbrowsergrouprowbehavior.livecodescript
  notes/bugfix-21834.md
Labels: vulcan/reviewed

#2003 [Bug 20701] Make manual height in PI consistent
  Toolset/palettes/behaviors/revinspectorbehavior.livecodescript
  Toolset/palettes/inspector/editors/com.livecode.pi.customprops.behavior.livecodescript
  Toolset/palettes/inspector/editors/com.livecode.pi.stackfiles.behavior.livecodescript
  Toolset/palettes/inspector/editors/com.livecode.pi.textcontents.behavior.livecodescript
  notes/bugfix-20701.md
Labels: vulcan/reviewed

#2054 Merge release 9.0.3 24.04.2019
  Toolset/palettes/start center/revStartCenterBehavior.livecodescript
  notes/bugfix-21856.md
Labels: pr/clean-merge, vulcan/reviewed
