Repository livecode/livecode-ide, pull requests merged in 2019-05, with the labels that each got.

#2056 Merge release 9.0.4 01.05.2019
  Toolset/palettes/start center/revStartCenterBehavior.livecodescript
  notes/bugfix-21856.md
Labels: pr/clean-merge, vulcan/reviewed

#2058 Merge develop 9.0 02.05.2019
  Toolset/palettes/behaviors/revinspectorbehavior.livecodescript
  Toolset/palettes/inspector/editors/com.livecode.pi.customprops.behavior.livecodescript
  Toolset/palettes/inspector/editors/com.livecode.pi.stackfiles.behavior.livecodescript
  Toolset/palettes/inspector/editors/com.livecode.pi.textcontents.behavior.livecodescript
  Toolset/palettes/project browser/behaviors/revideprojectbrowsercontainerrowbehavior.livecodescript
  Toolset/palettes/project browser/behaviors/revideprojectbrowsercontrolrowbehavior.livecodescript
  Toolset/palettes/project browser/behaviors/revideprojectbrowsergrouprowbehavior.livecodescript
  Toolset/palettes/script editor/behaviors/revsecommoneditorbehavior.livecodescript
  Toolset/palettes/start center/revStartCenterBehavior.livecodescript
  notes/bugfix-20701.md
  notes/bugfix-21834.md
  notes/bugfix-21856.md
  notes/bugfix-21896.md
Labels: pr/clean-merge, vulcan/reviewed

#1994 [[ Bug ]] Fix alloc & init handler definitions
  Documentation/guides/Extending LiveCode.md
Labels: vulcan/reviewed

#2050 [[ Bug 21484 ]] Allow scroll wheel to work in PI text fields
  Toolset/palettes/inspector/behaviors/revinspectoreditorbehavior.livecodescript
  notes/bugfix-21484.md
Labels: vulcan/reviewed

#2057 [22014] Don't show dialog about closing the last stack in file when building a standalone
  Toolset/libraries/revfrontscriptlibrary.livecodescript
  notes/bugfix-22014.md
Labels: vulcan/reviewed

#2055 [21969] Reset the templategroup before creating the tools palette
  Toolset/palettes/tools/revtools.livecodescript
  notes/bugfix-21969.md
Labels: bug, vulcan/reviewed

#2059 [[ Deploy Docs ]] Update deployment docs
  Documentation/guides/Deploying Your Application.md
  Documentation/guides/images/standalone-settings-android.png
  Documentation/guides/images/standalone-settings-html5.png
  Documentation/guides/images/standalone-settings-ios-basic.png
  Documentation/guides/images/standalone-settings-ios-icons.png
  Documentation/guides/images/standalone-settings-ios-requirements.png
  Documentation/guides/images/standalone-settings-ios-splash.png
  Documentation/guides/images/standalone-settings-windows.png
Labels: vulcan/reviewed

#2020 [[ Win 64 ]] Add support for building win64 standalones
  Toolset/libraries/revbackscriptlibrary.livecodescript
  Toolset/palettes/standalone settings/revstandalonesettings.8.rev
  Toolset/palettes/standalone settings/revstandalonesettingsbehavior.livecodescript
  Toolset/palettes/standalone settings/revstandalonesettingswindowsbehavior.livecodescript
Labels: vulcan/reviewed

#2053 refine revinspectorbehavior re manualHeight
  Toolset/palettes/behaviors/revinspectorbehavior.livecodescript
  Toolset/palettes/inspector/editors/com.livecode.pi.customprops.behavior.livecodescript
Labels: vulcan/reviewed

#2060 [22036] Allow setting the label of a graphic from the Property Inspector
  Toolset/resources/supporting_files/property_definitions/com.livecode.interface.classic.CurveGraphic.tsv
  Toolset/resources/supporting_files/property_definitions/com.livecode.interface.classic.LineGraphic.tsv
  Toolset/resources/supporting_files/property_definitions/com.livecode.interface.classic.OvalGraphic.tsv
  Toolset/resources/supporting_files/property_definitions/com.livecode.interface.classic.PolygonGraphic.tsv
  Toolset/resources/supporting_files/property_definitions/com.livecode.interface.classic.RectangleGraphic.tsv
  Toolset/resources/supporting_files/property_definitions/com.livecode.interface.classic.RegularGraphic.tsv
  Toolset/resources/supporting_files/property_definitions/com.livecode.interface.classic.RoundRectGraphic.tsv
  notes/bugfix-22036.md
Labels: enhancement, vulcan/reviewed

#2061 [22033] Keep value of global props linkcolor and underlinelink
  Toolset/palettes/start center/revStartCenterBehavior.livecodescript
  notes/bugfix-22033.md
Labels: bug, vulcan/reviewed

#1995 [[ Module Lcext ]] Update docs for static linking on iOS
  Documentation/guides/Extending LiveCode.md
Labels: documentation, vulcan/reviewed

#2062 Merge develop 9.0 13.05.2019
  Documentation/guides/Extending LiveCode.md
  Toolset/libraries/revfrontscriptlibrary.livecodescript
  Toolset/palettes/behaviors/revinspectorbehavior.livecodescript
  Toolset/palettes/inspector/editors/com.livecode.pi.customprops.behavior.livecodescript
  Toolset/palettes/script editor/behaviors/revsefindmaincardbehavior.livecodescript
  Toolset/palettes/start center/revStartCenterBehavior.livecodescript
  Toolset/palettes/tools/revtools.livecodescript
  Toolset/resources/supporting_files/property_definitions/com.livecode.interface.classic.CurveGraphic.tsv
  Toolset/resources/supporting_files/property_definitions/com.livecode.interface.classic.LineGraphic.tsv
  Toolset/resources/supporting_files/property_definitions/com.livecode.interface.classic.OvalGraphic.tsv
  Toolset/resources/supporting_files/property_definitions/com.livecode.interface.classic.PolygonGraphic.tsv
  Toolset/resources/supporting_files/property_definitions/com.livecode.interface.classic.RectangleGraphic.tsv
  Toolset/resources/supporting_files/property_definitions/com.livecode.interface.classic.RegularGraphic.tsv
  Toolset/resources/supporting_files/property_definitions/com.livecode.interface.classic.RoundRectGraphic.tsv
  notes/bugfix-21414.md
  notes/bugfix-21969.md
  notes/bugfix-22014.md
  notes/bugfix-22033.md
  notes/bugfix-22036.md
Labels: vulcan/reviewed

#2063 [[ Bugfix MultipleLCBDeps ]] Added chained LCB dep checking
  Toolset/libraries/revideextensionlibrary.livecodescript
Labels: vulcan/reviewed

#2064 [[ Bug ]] Fix extension dependency ordering
  Toolset/libraries/revideextensionlibrary.livecodescript
Labels: blocker, bug, vulcan/reviewed

#2065 [[ FasterDG ]] Use container layerMode in form view
  Toolset/palettes/revdatagridlibrary/behaviorsdatagridbuttonbehavior.livecodescript
  Toolset/resources/supporting_files/property_definitions/com.livecode.interface.classic.DataGridForm.tsv
  notes/feature-faster_dg.md
Labels: enhancement, vulcan/reviewed

#2068 [[ Bug ]] Add missing layerMode to inspector
  Toolset/resources/supporting_files/property_definitions/com.livecode.interface.classic.CurveGraphic.tsv
  Toolset/resources/supporting_files/property_definitions/com.livecode.interface.classic.Group.tsv
  Toolset/resources/supporting_files/property_definitions/propertyInfo.tsv
Labels: bug, vulcan/reviewed

#2067 [22091] Ensure selecting the same SVG icon does not cause the icon to disappear
  Toolset/palettes/inspector/editors/com.livecode.pi.svgiconfilter.behavior.livecodescript
  notes/bugfix-22091.md
Labels: bug, vulcan/reviewed

#2018 [[ BFS ]] Fix toolchain path when running from repo
  Toolset/libraries/revidelibrary.8.livecodescript
Labels: vulcan/reviewed
