Repository livecode/livecode-ide, pull requests merged in 2020-04, with the labels that each got.

#2120 [Bug 22627] Fix moving breakpoints w/ deleting
  Toolset/palettes/script editor/behaviors/revsegutterbehavior.livecodescript
  notes/bugfix-22627.md
Labels: vulcan/reviewed

#2125 [22655] Ensure upload of a .livecode stack is possible in revOnline
  Toolset/palettes/revonline.rev
  notes/bugfix-22655.md
Labels: bug, vulcan/reviewed

#2124 [[ Bug 22605 ]] Add iOS storyboard properties
  Documentation/guides/Deploying Your Application.md
  Documentation/guides/images/standalone-settings-ios-splash.png
  Toolset/palettes/standalone settings/revstandalonesettings.8.rev
  Toolset/palettes/standalone settings/revstandalonesettingsiosbehavior.livecodescript
Labels: blocker, enhancement, vulcan/reviewed

#2130 [[ Bug 22605 ]] Add dark mode options for iOS launch screen
  Documentation/guides/Deploying Your Application.md
  Documentation/guides/images/standalone-settings-ios-splash.png
  Toolset/palettes/standalone settings/revstandalonesettings.8.rev
  Toolset/palettes/standalone settings/revstandalonesettingsiosbehavior.livecodescript
Labels: enhancement, vulcan/reviewed
