Repository livecode/livecode-ide, pull requests merged in 2020-11, with the labels that each got.

#2148 [[ Bug 22847 ]] Improve display of enum values in dictionary
  Documentation/html_viewer/js/dictionary_functions.js
  notes/bugfix-22847.md
Labels: bug, documentation, vulcan/reviewed

#2149 [[ Bug 22897 ]] Ensure script colorization is preserved on Big Sur
  Toolset/resources/supporting_files/fonts/SourceCodePro-Black.ttf
  Toolset/resources/supporting_files/fonts/SourceCodePro-BlackIt.ttf
  Toolset/resources/supporting_files/fonts/SourceCodePro-Bold.ttf
  Toolset/resources/supporting_files/fonts/SourceCodePro-BoldIt.ttf
  Toolset/resources/supporting_files/fonts/SourceCodePro-ExtraLight.ttf
  Toolset/resources/supporting_files/fonts/SourceCodePro-ExtraLightIt.ttf
  Toolset/resources/supporting_files/fonts/SourceCodePro-It.ttf
  Toolset/resources/supporting_files/fonts/SourceCodePro-Light.ttf
  Toolset/resources/supporting_files/fonts/SourceCodePro-LightIt.ttf
  Toolset/resources/supporting_files/fonts/SourceCodePro-Medium.ttf
  Toolset/resources/supporting_files/fonts/SourceCodePro-MediumIt.ttf
  Toolset/resources/supporting_files/fonts/SourceCodePro-Regular.ttf
  Toolset/resources/supporting_files/fonts/SourceCodePro-Semibold.ttf
  Toolset/resources/supporting_files/fonts/SourceCodePro-SemiboldIt.ttf
  notes/bugfix-22897.md
Labels: bug, vulcan/reviewed

#2150 Merge develop 9.6 19.11.2020
  Documentation/dictionary/datagrid.lcdoc
  Documentation/html_viewer/js/dictionary_functions.js
  Toolset/home.livecodescript
  Toolset/libraries/revbackscriptlibrary.livecodescript
  Toolset/libraries/revcommonlibrary.livecodescript
  Toolset/libraries/revprintlibrary.livecodescript
  Toolset/palettes/inspector/editors/com.livecode.pi.customprops.behavior.livecodescript
  Toolset/palettes/revdatagridlibrary/bahaviorsswipecontrolholderbehavior.livecodescript
  Toolset/palettes/revdatagridlibrary/behaviorsdatagridbuttonbehavior.livecodescript
  Toolset/palettes/standalone settings/revstandalonesettings.8.rev
  Toolset/palettes/standalone settings/revstandalonesettingsmacbehavior.livecodescript
  Toolset/resources/supporting_files/fonts/SourceCodePro-Black.ttf
  Toolset/resources/supporting_files/fonts/SourceCodePro-BlackIt.ttf
  Toolset/resources/supporting_files/fonts/SourceCodePro-Bold.ttf
  Toolset/resources/supporting_files/fonts/SourceCodePro-BoldIt.ttf
  Toolset/resources/supporting_files/fonts/SourceCodePro-ExtraLight.ttf
  Toolset/resources/supporting_files/fonts/SourceCodePro-ExtraLightIt.ttf
  Toolset/resources/supporting_files/fonts/SourceCodePro-It.ttf
  Toolset/resources/supporting_files/fonts/SourceCodePro-Light.ttf
  Toolset/resources/supporting_files/fonts/SourceCodePro-LightIt.ttf
  Toolset/resources/supporting_files/fonts/SourceCodePro-Medium.ttf
  Toolset/resources/supporting_files/fonts/SourceCodePro-MediumIt.ttf
  Toolset/resources/supporting_files/fonts/SourceCodePro-Regular.ttf
  Toolset/resources/supporting_files/fonts/SourceCodePro-Semibold.ttf
  Toolset/resources/supporting_files/fonts/SourceCodePro-SemiboldIt.ttf
  Toolset/resources/supporting_files/property_definitions/com.livecode.interface.classic.Stack.tsv
  notes/bugfix-15638.md
  notes/bugfix-22285.md
  notes/bugfix-22727.md
  notes/bugfix-22847.md
  notes/bugfix-22873.md
  notes/bugfix-22897.md
  notes/bugfix-22903.md
Labels: vulcan/reviewed
