Repository livecode/livecode-ide, pull requests merged in 2021-06, with the labels that each got.

#2157 [[ Bug 23221 ]] Show names in SVG Icon Picker in Properties Inspector
  Toolset/palettes/inspector/editors/com.livecode.pi.svgiconfilter.behavior.livecodescript
  notes/bugfix-23221.md
Labels: vulcan/reviewed

#2156 [[ Bug 23219 ]] Extensionbuilder fix arrayKeys for default script and…
  Toolset/palettes/extension builder/revextensionbuilderbehavior.livecodescript
  notes/bugfix-23219.md
Labels: vulcan/reviewed

#2158 Merge develop 9.6 08.06.2021
  Documentation/dictionary/datagrid.lcdoc
  Toolset/palettes/extension builder/revextensionbuilderbehavior.livecodescript
  Toolset/palettes/inspector/editors/com.livecode.pi.svgiconfilter.behavior.livecodescript
  Toolset/palettes/project browser/revprojectbrowserbehavior.livecodescript
  Toolset/palettes/standalone settings/revstandalonesettings.8.rev
  Toolset/palettes/standalone settings/revstandalonesettingsandroidbehavior.livecodescript
  Toolset/palettes/standalone settings/revstandalonesettingsiosbehavior.livecodescript
  notes/bugfix-22300.md
  notes/bugfix-22400.md
  notes/bugfix-23202.md
  notes/bugfix-23219.md
  notes/bugfix-23221.md
Labels: pr/clean-merge, vulcan/reviewed

#2159 [[ Bug 22400 ]] Allow toggling the "allow http" setting
  Toolset/palettes/standalone settings/revstandalonesettings.8.rev
Labels: bug, vulcan/reviewed

#2155 [Bugfix-22979] Add dgRectofIndex to DataGrid docs
  Documentation/dictionary/datagrid.lcdoc
  notes/bugfix-22979.md
Labels: enhancement, vulcan/reviewed
